apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tgi-model-cache-pvc
spec:
  storageClassName: oci-bv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tgi-shm-pvc
spec:
  storageClassName: oci-bv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi