apiVersion: v1
kind: Service
metadata:
  name: tgi-service
  labels:
    app: tgi
spec:
  type: LoadBalancer
  selector:
    app: tgi
  ports:
    - protocol: TCP
      port: 80 # External port
      targetPort: 80 # Internal container port for the TGI service
